### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by sonilala** [Brawrdon/.com#2]
On the support page change "to use AdBlock", "if you go this link" and "price for ad space on the site will increasing". Contact me if you are unsure what to change these to.
One of your quotes about Pumpkin spice should say "tastes" instead of "taste".
Your coding skills page should say "I am *making* constant use.." under BASH.
On your page about Intarsia Moments make "mum" lowercase.

**Comment by Brawrdon** [comment]
Edits have been made and pushed to master!
